eProsima/Fast-DDS-python

fastdds_python_examples/HelloWorldExample/CMakeLists.txt
fastdds_python_examples/HelloWorldExample/HelloWorld.cxx
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx

Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>

Update type support with Fast DDS-Gen v2.1.1 [13785]

---

.github/workflows/build_and_test.yml

This PR adds a workflow for running CI in Ubuntu 20.04

Add Ubuntu CI [14066]

---

.github/workflows/build_and_test.yml

This PR removes the hard-coded Fast DDS in CI.
* Merge after eProsima/Fast-DDS#2560

Remove custom Fast DDS branch in CI [14066]

---

fastdds_python/CMakeLists.txt

This PR bumps the `fastdds_python` project version to v1.0.1

Bump version to v1.0.1

---

fastdds_python/src/swig/fastdds.i
fastdds_python/src/swig/fastdds/dds/domain/DomainParticipant.i
fastdds_python/src/swig/fastdds/dds/domain/DomainParticipantFactory.i
fastdds_python/src/swig/fastdds/dds/publisher/DataWriter.i
fastdds_python/src/swig/fastdds/dds/publisher/Publisher.i
fastdds_python/src/swig/fastdds/dds/subscriber/DataReader.i
fastdds_python/src/swig/fastdds/dds/subscriber/Subscriber.i
fastdds_python/test/CMakeLists.txt
fastdds_python/test/api/test_datareader.py
fastdds_python/test/api/test_datawriter.py
fastdds_python/test/api/test_domainparticipant.py
fastdds_python/test/api/test_publisher.py
fastdds_python/test/api/test_subscriber.py

Due to listeners are objects created directly on Python. Python manages them and it could delete them while they are been used internally by Fast DDS.
This PR fixes this increasing the internal Python references counter when the listeners are set to be used by Fast DDS, and decreasing them when Fast DDS leaves to use them.
This PR depends on be rebased over:
* #19

[14149] Fix ownership problem with listeners

---

fastdds_python/src/swig/fastdds/dds/domain/DomainParticipant.i
fastdds_python/src/swig/fastdds/dds/domain/DomainParticipantFactory.i
fastdds_python/src/swig/fastdds/dds/publisher/Publisher.i
fastdds_python/src/swig/fastdds/dds/subscriber/Subscriber.i
fastdds_python/test/api/DEFAULT_FASTRTPS_PROFILES.xml
fastdds_python/test/api/test_domainparticipant.py
fastdds_python/test/api/test_domainparticipantfactory.py
fastdds_python/test/api/test_publisher.py
fastdds_python/test/api/test_subscriber.py

Depends on the rebase over:
* #20

[14152] Add tests for `with_profile` API functions

---

fastdds_python/test/api/test_datawriter.py

Method DataWriter::get_key_value was implemented on Fast DDS, but the python binding tests still expected `UNSUPPORTED` to be returned. This PR adds proper tests for that API.

[14513] Tests for DataWriter.get_key_value

---

fastdds_python/test/api/test_datareader.py
fastdds_python/test/api/test_domainparticipant.py
fastdds_python/test/api/test_subscriber.py

Some test were failing due to the following:
`find_topic` is no longer unsupported.
`create_readcondition` and `create_querycondition` now receive masks instead of vectors.
Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>

Fix DomainParticipant and DataReader tests failing due to API changes

---

fastdds_python/test/api/test_domainparticipant.py

`DomainParticipant::ignore_participant` was implemented with Fast DDS release 2.10.1 but the matching Fast DDS-Python test was not updated.

[18057] Fix ignore participant check

---

fastdds_python.repos

eProsima/Fast-CDR#156 inlcudes API breaks in Fast CDR which make it incompatible with Fast DDS until eProsima/Fast-DDS#3828 is merged. Until then, this repository should use Fast CDR 1.1.x

[19461] Set Fast CDR version to 1.1.x

---

.github/ci/ccache.ps1
.github/workflows/build_and_test.yml
fastdds_python.repos
fastdds_python/CMakeLists.txt

**Warning:** Instead of generate VS solutions, with this PR Ninja solutions are generated.
Depends on:
- eprosima/eprosima-ci#37

Fix windows ccache [19657]

---

fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesPubSubTypes.cxx
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx

This PR regenerates the example types and the test types.
This is needed to introduce the Fast DDS Gen release v3.2.1 changes.

[20176] Regenerate Fast DDS docs example types due to Gen release v3.2.1

---

.github/workflows/build_and_test.yml

This PR updates the usage of:
- `colcon_test` action to cope with API break introduced in eProsima-CI v0.7.0
- Fix version of OpenSSL in Windows CI to 3.1.1 so Fast DDS builds

[20255] Update usage of eProsima CI actions

---

fastdds_python.repos

The `fastdds_python.repos` file had a typo in the fastdds_python section
This PR fixes it

[20023] Set proper version on fastdds_python.repos

---

fastdds_python/src/swig/fastrtps/types/TypesBase.i

This PR backports in 1.0.x the fix introduced here
- #73

[20486] Fix redefinition of _wrap___eq__ (backport #73)

---

fastdds_python.repos
fastdds_python/CMakeLists.txt

This PR bumps the version to 1.0.2 and set the proper fixed versions in the .repos file for 1.0.x (wrongly setup to master/main).

[20486] Bump version to v1.0.2 & update .repos

---

fastdds_python/src/swig/fastdds.i
fastdds_python/src/swig/fastdds/LibrarySettings.i
fastdds_python/src/swig/fastdds/dds/domain/DomainParticipant.i
fastdds_python/src/swig/fastdds/dds/subscriber/Subscriber.i
fastdds_python/test/types/test_complete.i
fastdds_python/test/types/test_included_modules.i
fastdds_python/test/types/test_modules.i
fastdds_python_examples/HelloWorldExample/HelloWorld.i

This PR accounts for changes in:
* eprosima/fast-dds#4500

[20569] Migrate DLL API exporter to fastdds

---

fastdds_python/test/types/CMakeLists.txt
fastdds_python/test/types/test_completev1.h
fastdds_python/test/types/test_included_modulesv1.h
fastdds_python/test/types/test_modulesv1.h
fastdds_python_examples/HelloWorldExample/HelloWorldv1.h

This PR updates the Fast DDS Python repo types according to the latest Fast DDS Gen released v3.3.0 version.

[20495] Regenerate types: Fast DDS Gen v3.3.0

---

fastdds_python/test/types/generate.sh
utils/scripts/update_generated_code_from_idl.sh

This PR adds a utility so that regenerating the repository various type supports is easier.

[20677] Add type support regeneration utility

---

fastdds_python_examples/HelloWorldExample/CMakeLists.txt
utils/scripts/update_generated_code_from_idl.sh

#108 generalized the script to autogenerate the code related to the types contained in the repository. This script did not take into account that the python types contained in the same folder overwrite the generated CMakeLists.txt file if not passed together to Fast DDS-Gen in the same command. This PR fixes this issue.
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- [N/A] Applicable backports have been included in the description.

[20734] Hotfix: type regeneration script

---

.github/pull_request_template.md
.github/workflows/build_and_test.yml
.github/workflows/mirror.yml
README.md
fastdds_python/CMakeLists.txt

This PR prepares the 3.0.x-devel branch to become Fast DDS Python main
- _N/A_: Changes are API compatible. 

[20893] Prepare 3.0.x-devel to become main

---

fastdds_python/test/types/test_completeTypeObjectSupport.cxx
fastdds_python/test/types/test_completeTypeObjectSupport.hpp
fastdds_python/test/types/test_included_modulesTypeObjectSupport.cxx
fastdds_python/test/types/test_included_modulesTypeObjectSupport.hpp
fastdds_python/test/types/test_modulesTypeObjectSupport.cxx
fastdds_python/test/types/test_modulesTypeObjectSupport.hpp
fastdds_python_examples/HelloWorldExample/HelloWorldTypeObjectSupport.cxx
fastdds_python_examples/HelloWorldExample/HelloWorldTypeObjectSupport.hpp

Regeneration of IDL source code to compile against eprosima/fast-dds#4746
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- *N/A* Applicable backports have been included in the description.

Automatic TypeObject representation registration for DynamicTypes [21058]

---

.github/workflows/build_and_test.yml

This PR uses a token for the setup-ccache action from in the CI, which is behind the CI failures on post steps due to exceeding github API usage rate limits
@Mergifyio backport 1.4.x 1.2.x 1.0.x
- _N/A_: Changes are API compatible.

[21168] Use token for ccache action

---

.github/workflows/test.meta
fastdds_python/test/api/test_domainparticipant.py
fastdds_python/test/api/test_domainparticipantfactory.py
fastdds_python/test/api/test_publisher.py
fastdds_python/test/api/test_qos.py
fastdds_python/test/api/test_subscriber.py

This PR adjusts for the changes introduced in:
* eProsima/Fast-DDS#4875

[21120] Adjust for API changes in RTPS reader APIs

---

fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_completePubSubTypes.h
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_included_modulesPubSubTypes.h
fastdds_python/test/types/test_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesPubSubTypes.h
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.h

This PR adjusts python bindings for:
* eProsima/Fast-DDS#4960

[21183] Adjust for `const` qualification of all data related inputs in DataWriter APIs

---

fastdds_python/src/swig/fastdds.i
fastdds_python/src/swig/fastdds/dds/domain/DomainParticipantFactory.i
fastdds_python/src/swig/fastdds/dds/domain/qos/DomainParticipantExtendedQos.i
fastdds_python/test/api/test_domainparticipantfactory.py

Python binding corresponding to Fast-DDS PR: https://github.com/eProsima/Fast-DDS/pull/4779
- _N/A_: Check CI results: failing tests are unrelated with the changes.

[20869] Create DomainParticipantExtendedQos.i 

---

fastdds_python/src/swig/fastdds/dds/domain/DomainParticipant.i
fastdds_python/src/swig/fastdds/dds/publisher/DataWriter.i
fastdds_python/src/swig/fastdds/dds/subscriber/DataReader.i
fastdds_python/src/swig/fastdds/rtps/common/InstanceHandle.i

This PR is the Fast DDS Python counterpart of:
* eProsima/Fast-DDS#5016
* eProsima/Fast-DDS-docs#796
@Mergifyio backport 1.2.x 1.0.x

[21114] Remove doxygen warnings (#121)

---

fastdds_python/CMakeLists.txt
fastdds_python/test/types/CMakeLists.txt
fastdds_python_examples/HelloWorldExample/CMakeLists.txt

Due to an error, fastdds_python doesn't compile with current SWIG version (4.2.0) on Ubuntu 24.04. The fix is in swig 4.2.1 but it's not accessible in ubuntu noble. This ubuntu also contains the package `swig4.1` but CMake is not prepare to find its executable. This PR fixes this using a trick.
Related to:
- eprosima/fast-dds-gen#364

[21270] Support compilation againt Ubuntu 24.04 swig4.1

---

fastdds_python/test/api/test_qos.py

This PR adapts the code to the RTPS writer APIs refactor. In particular, the rename of members in `WriterTimes`.
Related implementation PR:
https://github.com/eProsima/Fast-DDS/pull/5028

[21137] Account for changes on RTPS writer refactor

---

fastdds_python/src/swig/fastdds/dds/core/policy/QosPolicies.i
fastdds_python/src/swig/fastdds/utils/collections/ResourceLimitedVector.i
fastdds_python/test/api/test_domainparticipant.py
fastdds_python/test/api/test_qos.py

Fixes next message:
```
swig/python detected a memory leak of type 'eprosima::fastrtps::ResourceLimitedVector< unsigned char >::pointer *', no destructor found.
```
@Mergifyio backport 1.4.x 1.2.x

Fix warning about memory leak in tests [21177]

---

fastdds_python/test/api/test_datareader.py
fastdds_python/test/api/test_datawriter.py

This PR is the corresponding applied to this repo the Fast DDS PR:
- https://github.com/eProsima/Fast-DDS/pull/5049

[21329] Update `DataWriter::write` return value as `ReturnCode_t`

---

fastdds_python/src/swig/fastdds/dds/domain/DomainParticipantFactory.i
fastdds_python/test/api/test_datareader.py
fastdds_python/test/api/test_datawriter.py
fastdds_python/test/api/test_domainparticipant.py
fastdds_python/test/api/test_domainparticipantfactory.py
fastdds_python/test/api/test_publisher.py
fastdds_python/test/api/test_subscriber.py

Running this repository's tests fail on Ubuntu 24.04 due to SWIG 4.1. This PR fixes them.
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- *N/A* Applicable backports have been included in the description.

[21383] Fix tests on Ubuntu 24.04

---

fastdds_python_examples/HelloWorldExample/CMakeLists.txt
utils/scripts/update_generated_code_from_idl.sh

This PR cherry-picks a set of commits that created and updated the type support regeneration utility to bring it to the version 1.2.x.
(Tested locally)
Related PR:
- https://github.com/eProsima/Fast-DDS-Gen/pull/368

[21226] Add type support regeneration utility to 1.2.x

---

.github/workflows/ubuntu-ci.yml
.github/workflows/windows-ci.yml

Fast DDS version 2.13.x is EOL. In this PR
- #162
It was removed from nightly jobs but the changes performed in this PR was missing in 1.4.x (removing testing with 2.13.x)

[21310] Remove 2.13.x from CI in 1.4.x version

---

fastdds_python/src/swig/fastdds.i
fastdds_python/test/CMakeLists.txt
fastdds_python/test/api/conftest.py
fastdds_python/test/api/test_datareader.py
fastdds_python/test/types/test_complete.i
fastdds_python/test/types/test_included_modules.i
fastdds_python/test/types/test_modules.i
fastdds_python_examples/HelloWorldExample/HelloWorld.i

This is the Fast DDS Python counterpart of:
* eprosima/fast-dds#5073
- _N/A_: Changes are API compatible. 

[21325] Remove all code related to FAST CDR v1

---

fastdds_python_examples/HelloWorldExample/HelloWorldExample.py

When updating the Fast DDS python code to the new TopicDataType methods, the HelloWorld example update was missed. This PR updates changes those calls to use the new API.
Fixes #182 
- ❌: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- We will update the CI so it runs the example in a follow-up
- ❌: Changes are API compatible. 

[21486] Fix HelloWorld example with TopicDataType refactored code

---

README.md
fastdds_python/test/types/test_completeCdrAux.ipp
fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_included_modulesCdrAux.ipp
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesCdrAux.ipp
fastdds_python/test/types/test_modulesPubSubTypes.cxx
fastdds_python_examples/HelloWorldExample/HelloWorldCdrAux.ipp
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx

This PR bumps the Fast DDS Python version to v2.0.0
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- N/A Changes are API compatible. 
- N/A Applicable backports have been included in the description.

[21366] Bump to v2.0.0

---

.github/pull_request_template.md
.github/workflows/mirror.yml
.github/workflows/nightly-ubuntu-ci.yml
.github/workflows/nightly-windows-ci.yml
fastdds_python/CMakeLists.txt

This PR bumps the project to `v2.2.0` and updates the workflows for the `branchout`.
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI results: failing tests are unrelated with the changes.

[21882] Bump version to 2.2.0

---

fastdds_python/test/api/test_datareader.py
fastdds_python/test/api/test_datawriter.py

This PR updates DataWriter/Reader `get_matched_publication/subscirption...()` tests in the `Fast DDS Python 2.x branch` as result of API implementation:
* eProsima/Fast-DDS#5312
**IMPORTANT**
This PR must be merged after 
* #193 

[21808] Update DataWriter/Reader `get_matched_publication/subscription...()` (2.x) API tests

---

fastdds_python/test/types/test_completeCdrAux.hpp
fastdds_python/test/types/test_completeCdrAux.ipp
fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_completePubSubTypes.hpp
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesCdrAux.hpp
fastdds_python/test/types/test_modulesCdrAux.ipp
fastdds_python/test/types/test_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesPubSubTypes.hpp
fastdds_python/test/types/test_modulesTypeObjectSupport.hpp
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx

This PR updates the generated types with `Fast DDS Gen v4.0.3`

[22497] Regenerate types with Fast DDS Gen 4.0.3

---

fastdds_python/test/types/test_complete.i
fastdds_python/test/types/test_completeCdrAux.hpp
fastdds_python/test/types/test_completeCdrAux.ipp
fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_completePubSubTypes.hpp
fastdds_python/test/types/test_included_modules.i
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modules.i
fastdds_python/test/types/test_modulesCdrAux.hpp
fastdds_python/test/types/test_modulesCdrAux.ipp
fastdds_python/test/types/test_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesPubSubTypes.hpp
fastdds_python/test/types/test_modulesTypeObjectSupport.hpp
fastdds_python_examples/HelloWorldExample/HelloWorld.i
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx

This PR updates types with Fast DDS Gen 4.0.4 in 2.1.x

[22858] Update types with Fast DDS Gen 4.0.4 (2.1.x)

---

fastdds_python/src/swig/fastcdr/cdr/fixed_size_string.i
fastdds_python/src/swig/fastdds.i

This PR add support for using `string_255` type in python applicatioons. 
It also fixes the following warnings get when participant listener functions are called:
```bash
swig/python detected a memory leak of type 'eprosima::fastdds::rtps::ParticipantDiscoveryStatus *', no destructor found.
swig/python detected a memory leak of type 'eprosima::fastdds::rtps::WriterDiscoveryStatus *', no destructor found.
swig/python detected a memory leak of type 'eprosima::fastdds::rtps::ReaderDiscoveryStatus *', no destructor found.
```
@Mergifyio backport 2.1.x 2.0.x

Add support for `string_255` type and fix discovery status memory leaks

---

fastdds_python/CMakeLists.txt

- **N/A** Check CI results: failing tests are unrelated with the changes.

[22800] Bump version to 2.1.1

---

fastdds_python/src/swig/fastdds/dds/rpc/interfaces.i
fastdds_python_examples/RPCExample/generated_code/calculator.i
fastdds_python_examples/RPCExample/generated_code/calculatorClient.cxx
fastdds_python_examples/RPCExample/generated_code/calculatorServer.cxx
fastdds_python_examples/RPCExample/generated_code/calculatorServer.hpp
fastdds_python_examples/RPCExample/generated_code/calculatorServerImpl.hpp

Expose the server and request interfaces from https://github.com/eProsima/Fast-DDS/pull/5873

[23325] Add generic interfaces for RPC servers
