fastdds_python/test/api/test_datareader.py

Datareader::lookup_instance was implemented in fastdds and this PR adds necessary tests for testing this functionality on python bindings.

Add test for new Datareader::lookup_instance [14561]

---

README.md

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

[14803] SWIG dependency requirement

---

fastdds_python/CMakeLists.txt

Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>

Bump version to v1.1.0

---

fastdds_python/src/swig/fastdds/dds/core/condition/Condition.i
fastdds_python/test/api/test_datareader.py
fastdds_python/test/api/test_waitset.py

Updated:
- DataReader testing
- WaitSet Testing
- Fix windows import issue on WaitSet testing.

[15319] Promote ReadCondition to supported

---

fastdds_python/test/api/test_waitset.py

Addressing https://github.com/eProsima/Fast-DDS-python/pull/37#discussion_r934211205

Refs 15319. Fix test coverage

---

fastdds_python/CMakeLists.txt

Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>

Bump version to v1.2.0

---

fastdds_python.repos

This PR sets the appropriate versions of the dependencies in fastdds_python.repos

Set versions on fastdds_python.repos

---

fastdds_python/src/swig/fastdds.i
fastdds_python/src/swig/fastdds/rtps/attributes/ThreadSettings.i

This PR adds support for Fast DDS ThreadSettingQos

[19645] Support Fast DDS' ThreadSettingsQos

---

.github/workflows/mirror.yml

This PR adds a mirror workflow to keep the same branching model approach as in Fast DDS

[20107] Add mirror workflow

---

.github/workflows/build_and_test.yml

This PR refactors the workflow to use more of eProsima CI actions

[20107] Refactor workflow

---

fastdds_python/CMakeLists.txt

This PR bumps the project version to 1.4.0

[20107] Bump to version v1.4.0

---

.github/pull_request_template.md
fastdds_python.repos
fastdds_python/CMakeLists.txt

This PR:
1. Bumps the project version to 1.4.1
2. Adds this PR template
- **N/A** Check CI results: failing tests are unrelated with the changes.

[20677] Bump version to 1.4.1

---

.github/workflows/build_and_test.yml

This PR updates of other products versions in the GitHub workflow to the last compatible ones
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- _N/A_ Changes are API compatible. 

[21030] Update GitHub workflow

---

fastdds_python.repos

This pr updates .repos file for version 1.4.x
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- _N/A_ Changes are API compatible. 

[19452] Update repos file

---

fastdds_python/CMakeLists.txt

This PR bumps Fast DDS Python version 1.4.x to v1.4.2

[21100] Bump Fast DDS Python version 1.4.x to v1.4.2

---

fastdds_python/test/api/test_qos.py

- This PR updates python tests to include the changes introduced in: https://github.com/eProsima/Fast-DDS/pull/4842 

[21077] Update Fast DDS docs QoS examples

---

.github/workflows/reusable-ubuntu-ci.yml
README.md
RELEASE_SUPPORT.md

[21228] Apply missing fixes in CI

---

.github/workflows/nightly-ubuntu-ci.yml
.github/workflows/nightly-windows-ci.yml
RELEASE_SUPPORT.md

This PR sets Fast DDS 2.13.x as EOL
- **N/A** Check CI results: changes do not issue any warning.
- **N/A** Check CI results: failing tests are unrelated with the changes.

[21310] Set Fast DDS 2.13.x as EOL

---

fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_completePubSubTypes.hpp
fastdds_python/test/types/test_completePubSubTypes.i
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_included_modulesPubSubTypes.hpp
fastdds_python/test/types/test_included_modulesPubSubTypes.i
fastdds_python/test/types/test_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesPubSubTypes.hpp
fastdds_python/test/types/test_modulesPubSubTypes.i
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.hpp
fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.i

This PR update the source code to new changes introduced in:
- eprosima/fast-dds-gen#375
- eprosima/fast-dds#5066
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- ❌ Applicable backports have been included in the description.

[21373] Update to new TopicDataType functions

---

.github/workflows/reusable-windows-ci.yml

The merge metas file eProsima CI action has been removed. This PR removes its usage.
@Mergifyio backport 1.4.x 1.2.x 1.0.x 
- **N/A** Changes are API compatible.

[21387] Avoid usage of removed action

---

fastdds_python/CMakeLists.txt

This bumps version on 1.2.x to 1.2.4
- _N/A_ Check CI results: changes do not issue any warning.
- _N/A_ Check CI results: failing tests are unrelated with the changes.

[21557] Bump version to 1.2.4

---

README.md

- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally

Use swig4.1 in Fast-DDS dependencies

---

.github/pull_request_template.md
.github/workflows/mirror.yml
.github/workflows/nightly-ubuntu-ci.yml
.github/workflows/nightly-windows-ci.yml
fastdds_python/CMakeLists.txt

This PR bumps the project to `v2.1.0` and updates the worksflows for the branchout.
- **N/A**  Changes are API compatible. 
- **N/A**  Applicable backports have been included in the description.

[21783] Bump version to 2.1.0

---

fastdds_python/CMakeLists.txt

Merge after: 
- https://github.com/eProsima/Fast-DDS-python/pull/198

[21560] Bump to version 1.4.3

---

fastdds_python/test/types/test_completePubSubTypes.cxx
fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
fastdds_python/test/types/test_modulesPubSubTypes.cxx

[21560] Regenerate types Fast-DDS-Gen v3.3.1

---

RELEASE_SUPPORT.md

This PR updates the RELEASE_SUPPORT file to include EOL versions

[22175] Add EOL versions in RELEASE_SUPPORT.md

---

fastdds_python/test/types/test_included_modules.i
fastdds_python_examples/HelloWorldExample/HelloWorld.i

This PR updates types with Fast DDS Gen 4.0.4

[22858] Update types with Fast DDS Gen 4.0.4

---

.github/workflows/reusable-ubuntu-ci.yml
.github/workflows/reusable-windows-ci.yml

This PR adds Fast CDR branch selection in jobs, similarly to how it is done in Fast DDS Ubuntu CI.
@Mergifyio backport 2.1.x 2.0.x 1.4.x 1.2.x 1.0.x
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally

[22955] Get correct Fast CDR related branch in CI

---

.github/workflows/reusable-ubuntu-ci.yml
.github/workflows/reusable-windows-ci.yml

This PR fixes a CI error caused by selecting a Fast CDR branch with the same name as the Fast DDS Python base branch, instead of using the specified `fallback_branch`.
- **NO** Commit messages follow the project guidelines. 

Skip base branch in Fast CDR branch selection

---

.github/pull_request_template.md
.github/workflows/nightly-ubuntu-ci.yml
.github/workflows/nightly-windows-ci.yml

This PR removes unneeded nigthly workflows and updates the PR template backport list removing the EOL `2.0.x` branch 

Updates due to `2.0.x` EOL branch

---

.github/pull_request_template.md
.github/workflows/mirror.yml
.github/workflows/nightly-ubuntu-ci.yml
.github/workflows/nightly-windows-ci.yml
fastdds_python/CMakeLists.txt

This PR branches out 2.3.x, including
* Bump version
* Update workflows with 2.2.x
* Adds 2.2.x to PR template

[23269] Branch out 2.3.x

---

fastdds_python/src/swig/CMakeLists.txt

Add new option BUILD_FOR_DEBIAN_PACKAGE

[23774] Add new option BUILD_FOR_DEBIAN_PACKAGE
